### ISSUE TITLE
Let's combine forces  ?

### ISSUE THREAD

**Issue by dmpe** [DataWookie/urlshorteneR#1]
Hi @DataWookie ,

I am a developer of https://cran.r-project.org/web/packages/RBitly/index.html & https://github.com/dmpe/rbitly and in the current version, which is on CRAN, it only supports Bit.ly. I have implemented most of its methods that are currently available (the non-premium ones) and the package uses a "normal" API key so no oauth2 support. 

At the moment I am trying to extend it with Ow.ly (already done, but very hard to test as I dont have the API key and they do not offer it anymore - i have asked already) and now goo.gl too. 

The name of the package is not very well chosen and renaming it would be very hard https://stackoverflow.com/questions/22654421/how-to-rename-an-existing-r-package-on-cran so maybe we could combine the forces to create one package which covers it all ? What do you think? Would you be interested ?

John (@dmpe)

**Comment by datawookie** [comment]
Hi John,

Thanks very much for the email. I am rather ashamed to say that I did not find your package on CRAN. From what I recall I searched the index for "shortener", found nothing and then started working on my package.

I would be very happy to join forces with you. However, I do think that it would make sense to try for a more generic package name since RBitly is a little restrictive if the package is going to cover multiple shorteners.

Best regards,
Andrew.

**Comment by dmpe** [comment]
Yes Andrew, 

That would be really great! So, definitely I would agree to "retire" my package if we could combine two package somehow. Once it would be finished, RBitly can  be "archived" and `urlshorteneR` would get replaced. Maybe (later) we can work with Bob from https://cran.r-project.org/web/packages/longurl/ to so the same. 

Services we would aim for:
- [x] Goo.gl (just one method is missing already, will wait for further development until we decide what & how to go further)
- [x] Bit.ly (everything free is covered, the rest depends on business API Key)
- [ ] Ow.ly (98%)
- [ ] Tinyurl
- [ ] LongUrl
- [x] is.gd

That is fairly big list. 

### Questions to answer/decide:

<strong>One</strong>
So, at first some ORG. things. Generally, I think it would be good if you would add me to this repository (from repo. settings). Please could you do so ? That would allow me to push directly to this repo without have to do constant PR. I promise to be careful !

Or even (maybe) better would be to add you to my repository (already added, but still open to discussion), which I would later rename to `urlshorteneR`. With this, we would spare refreshing all the links because of github's flexibility with URLs when renaming repositories.

Thus, all the "infra" (tests, travis etc.) would be already in place and you would later just retire this repo in favour of mine, which I would rename to urlshorteneR. Would you agree ?

<strong>Second</strong>
At the first stage, everything needs be updated in regards to links in readme, travis, description files etc. (depends on the above, if at all). That is fairly easy. 
But then comes the harder part: as I said, my `RBitly` works only with API key, which the user must get. It is this HTTP Basic Authentication Flow, not the OAUTH2. 
What would be your idea to do here ? I guess, we do want to use only OAUTH2 where it is available and HTTP Basic API Key where there is no such possibility? Meaning, we use only OAUTH2 for bitly & goo.gl.

**Comment by dmpe** [comment]
<strong>Three</strong>
Also, do you want to use some OO system such as `S3`, `R6` etc. https://cran.r-project.org/web/packages/R6/index.html ? I dont have experience with any of them, but can imagine it would have some benefits. 
TODO: Investigate this pckg: https://github.com/MarkEdmondson1234/googleAuthR

<strong>Four</strong>

Given that there will be always some shortening and expanding functionality in each of the services above, <strong>one option</strong> would be to use a very general methods like:

```
# will recognize automatically (from the url) what service it will use or we can just always use http://longurl.org/
expand <- function(longURL = string) 

shorten <- function(shortURL = string, service = "goo.gl")
```

<strong>OR</strong> we can use specific methods for each service (I guess I would be in favor of this one). Like: 

```
links_Expand_Bitly <- function(longURL = string) (not using the longurl.org)
links_Shorten_Bitly <- function(shortURL = string)
```

This has an additional advantage of being service specific. In either case, most of the methods are service specific, thus <strong>consistent naming</strong> would be required. 
For my `RBitly` I have used `links_Shorten` & `links_Expand` for bit.ly and `links_ShortenOwly` etc. for other services. 

Here, we could also use https://github.com/hrbrmstr/longurl (this uses `dplyr`). 

<strong>Five</strong>
How do we name R files (and functions)? And do we name them after their general functionality (e.g. `UserMetrics.R`, `LinksMetrics`) or after the each service (e.g. Bitly_Links, Google_Links) ? (bit.ly file would be huge, whereas google file would include only 3 methods)

<strong>Six (ignore)</strong>
See here:https://github.com/hadley/httr/blob/master/demo/oauth2-google.r

~~Let's say the user will authenticate using OAUTH2 with bitly using this logic https://github.com/DataWookie/urlshorteneR/blob/master/R/oauth.R. This will consequently assign httr.oauth file to the R environment, so something like this below.~~
![selection_002](https://cloud.githubusercontent.com/assets/1799661/10117963/c8632cb6-6469-11e5-871f-40194b82e0a5.png)
~~Then, lets say the user will need to access goo.gl, so he does the same. In the httr.oauth file this will be stored on -1 position. Thus, you would have two lists. The issue is how do you access different keys, which are different for each service and naming is not helpful at all.~~
![selection_003](https://cloud.githubusercontent.com/assets/1799661/10117968/328e800e-646a-11e5-98d2-bbf81805f925.png)
~~Here, which one is for bitly and which one is for goo.gl ? I am not sure if I have expressed myself good enough, but do you see my point ? Basically, you don’t know which one to access for each service, because names you can use are meaningless.~~

```
httr_tokens <- readRDS('.httr-oauth')
httr_tokens$ba0fac5b870d2ab06368568b13f8abdd (googl)
httr_tokens$a545c927eefccadb7ea88a40a1160408 (bitly)
```

**Comment by datawookie** [comment]
Hi John,

Just to let you know that I have seen your messages above. It's a holiday weekend in South Africa though, so I am doing my best to please my wife and not spend my time in the study. I'll get back to you on Monday.

Best regards,
Andrew.

**Comment by dmpe** [comment]
Thank you, Andrew, very much for this information ! Enjoy the holidays!
And, please once you will be reading this, <strong>start from the beginning of this thread</strong> because I made it much more understandable, hopefully. 

Some smaller things have been already done in https://github.com/dmpe/rbitly/tree/comb

API file: https://github.com/dmpe/rbitly/blob/comb/R/ApiKey.R
A working example: https://github.com/dmpe/rbitly/blob/comb/R/Domains.R#L20

**Comment by dmpe** [comment]
@DataWookie Hi Andrew, any update on this ? Thanks

**Comment by datawookie** [comment]
Hi John,

Sorry I have taken so long to get back to you. I picked up gastic 'flu at the beginning of the week and I have been out of action since then. So, in answer to the specific issues you pose above:

One: I am quite happy to work from your repository.

Two: It's going to be a bit tricky working with both OAuth and OAuth2, but to get the full functionality from some of these services OAuth2 is the only option. If we are going to support both then we will need to figure out a way to do this which is not too clunky.

Three: I think that an OO structure would be a good idea, especially in light of the fact that we are going to be implementing a bunch of services which have essentially a similar interface. I also am not an expert on any of R's OO techniques, but I am sure that we could figure this out without too much sweat.

Four: If we go the OO route then this should be a moot point, shouldn't it?

Five: I am in favour of having the functionality broken down by service, so we would have a bitly.R file etc.

I should warn you at this stage that I am really strapped for time right now, so I am not sure how much of this work I will be able to do in the near future.

Have a great weekend!

Best regards,
Andrew.

**Comment by dmpe** [comment]
Hi Andrew, 
Ohh, that is really bad ! As your health will allow you to work on this, let me know and as being said you have full push access to me RBItly repo. 
Until then, I am going to slowly getting into the learning of some OO system (I think i will stick to the basic one - S3) and will contribute further ahead our mission. 

Two: Goo.gl & bit.ly are going to use only OAUTH2, whereas for example Ow.ly the basic authen.
Five: Definitely, for bitly it is necessary to have several files as it has the most methods to implement. 

Once ready, I will propose something here. 
Thanks again for your response. And I wish you speedy recovery!

**Comment by datawookie** [comment]
Hi John,

I was thinking about this a bit further on the way home. Perhaps it is a mistake to try and target too many different URL shortening services. We should probably focus our attention on only a handful and do a good job on them. It would be helpful if the handful we chose also had a consistent authentication protocol.

Best regards,
Andrew.

**Comment by dmpe** [comment]
Hi Andrew, 
I agree, therefore I want to target only 3 for the beginning: bitly, google and owly (now seems dead to me, will switch to is.gd). These, I have the feeling ,are the most used on the internet. 
Additionally, even though we are not going to provide shortening cabalities for all services out there, we can use LongURL.org to enable users to see their long URLs as well. 

> had a consistent authentication protocol

Well, that depends on the service. For example, both google and bitly offer basic auth with url =API Key as well as the OAUTH2 based one, which you have already implemented. 

Best, J.

**Comment by dmpe** [comment]
Hi Andrew, 
(read once you will be ready to do so)

### OO

After reading chapters about different OO system here:http://adv-r.had.co.nz/OO-essentials.html and here http://adv-r.had.co.nz/S3.html, I am still unsure what advantage would OO bring us. Please, later, if you can, take a look at this too. Thanks

Otherwise, I have commited changes to the branch here https://github.com/dmpe/rbitly/tree/comb, with all the changes.

**Comment by dmpe** [comment]
Hi @DataWookie, 
just to let you know: I am about to finish the work on it and will release the new package (and retire the old one) on CRAN sometime in November.

**Comment by datawookie** [comment]
Hi John,

This is great news. You have obviously been working hard on this! Thank you.

Please let me know what still remains outstanding and how you would like me to contribute.

Best regards,
Andrew.

**Comment by dmpe** [comment]
Hi Andrew,
I dont know. For real. There are multiple issues - first I decided not to use any OO system, although I would like very much. 

Then, there are issue with the testing on cran/travis because authentication requires "interactive" mode (e.g. you and browser). This means every test is not functional on travis/cran and the best way to fix that was/is - most probably - this: https://github.com/jennybc/googlesheets/blob/master/internal-projects/10_token-encryption.Rmd Basically write `rds` and then read it back on travis. 
I tried a lot, but still was not able to cope with tests + vignettes (and changing directories) so that everything would function well. 

Given that you have full commit access, feel free to play around with anything. Also, dont forget to add yourself into the authorship section of the description file. 
Any help is always appreciated. 

Best, John

**Comment by datawookie** [comment]
Hi John,

Okay, I know absolutely nothing about Travis, so I am not sure how much help I can be there.

After you initially got in contact I did at least make a start on the framework for an OO implementation. I have started a new branch at https://github.com/DataWookie/urlshorteneR/tree/refclass where you can see the basic outline in refclass.R. Very early stages, but this is the basic idea: have a reference class for each type of URL shortener, which would then be derived from a common ancestor. So the interface presented by each of the classes would be consistent.

What do you think?

Regards,
Andrew.

**Comment by dmpe** [comment]
Are you sure that it woudn't be easier to do with http://adv-r.had.co.nz/S3.html which is used more commonly? I mean do we need something from RefClasses that we dont have in S3 or vice versa ?
